version: '2'

services:
  eureka-server:
    image: sebas1411/eureka-server:v2
    ports:
      - "8761:8761"

  zuul-server:
    image: sebas1411/zuul-server:v4
    ports:
      - "8090:8090"
    depends_on:
      - eureka-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka

  microservicio-empresa:
    image: sebas1411/microservicio-empresa:v2
    ports:
      - "8890:8890"
    depends_on:
      - eureka-server
      - zuul-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka
      spring.datasource.url: jdbc:postgresql://172.21.101.55:5432/sampledb
      spring.datasource.username: postgresadmin
      spring.datasource.password: Passw0rd2020 

  microservicio-persona:
    image: sebas1411/microservicio-persona:v2
    ports:
      - "8060:8060"
    depends_on:
      - eureka-server
      - zuul-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka
      spring.datasource.url: jdbc:postgresql://172.21.101.55:5432/sampledb
      spring.datasource.username: postgresadmin
      spring.datasource.password: Passw0rd2020

  microservicio-transaccion:
    image: sebas1411/microservicio-transaccion:v2
    ports:
      - "8020:8020"
    depends_on:
      - eureka-server
      - zuul-server
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka
      spring.datasource.url: jdbc:postgresql://172.21.101.55:5432/sampledb
      spring.datasource.username: postgresadmin
      spring.datasource.password: Passw0rd2020