apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: microservicio-transacciones
  name: microservicio-transacciones
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: sebas1411/microservicio-transaccion:v1
      generation: null
      importPolicy: {}
      name: v1
      referencePolicy:
        type: ""
status:
  dockerImageRepository: ""
