apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: zuul-server
  name: zuul-server
spec:
  lookupPolicy:
    local: false
  tags:
    - annotations: null
      from:
        kind: DockerImage
        name: sebas1411/zuul-server:v5
      generation: null
      importPolicy: {}
      name: v5
      referencePolicy:
        type: ""
status:
  dockerImageRepository: ""
